universe = container
container_image = tb-profiler-test.sif
transfer_executable = false

executable = /opt/conda/bin/tb-profiler
arguments = profile -1 $(sequence_read)_1.fastq -2 $(sequence_read)_2.fastq -t 1 -p $(sequence_read)

should_transfer_files = yes
data_path = osdf:///osgconnect/public/osg/tutorial-tb-profiler/tb-sra-files/$(sequence_read)
transfer_input_files = $(data_path)/$(sequence_read)_1.fastq, $(data_path)/$(sequence_read)_2.fastq, osdf:///osgconnect/public/osg/tutorial-tb-profiler/tb-profiler-test.sif
output_file = $(sequence_read).results.json
transfer_output_files = results/$(output_file)
transfer_output_remaps = "$(output_file) = outputs/$(output_file)"

log = logs/tb-profiler.log
error = logs/$(sequence_read).$(Cluster).$(Process).err
output = logs/$(sequence_read).$(Cluster).$(Process).out

requirements = (Target.has_avx == true)

request_cpus = 1
request_memory = 4GB
request_disk = 4GB

sequence_read = SRR18714896
queue 1
#queue sequence_read from SraAccList.csv
